#ifndef MTL_H_
#define MTL_H_

// .mtl file coupled with a .obj file generated by a 3D Modelling program
#include "../../Math/struct/vertex.h"
#include "../CharString.h"
#include "../LinkedList.hpp"
#include "../../Parsing/SimpleParser.h"
#include "../../Design/Model/IMaterial.h"
#include <stdlib.h>

#define COUT_MAT_DEBUG

#ifdef COUT_MAT_DEBUG
	#define debugLogmm(s) cout << s << endl; cout.flush()
#else
	#define debugLogmm(s)  //nothing
#endif


using namespace std;

class MTL{
public:
    MTL(){}
    ~MTL(){}


    static LinkedList<IMaterial*> loadFromFile(CharString mtlFile);
};



#endif
