#ifndef INJURY_H_
#define INJURY_H_

enum INJURYTYPE {IT_BURN, IT_CUT, IT_STAB, IT_BLUNT};
enum INJURYLOC {IL_HEAD, IL_LARM, IL_RARM, IL_LHAND, IL_RHAND, IL_CHEST, IL_ABDOMEN, IL_CROTCH, IL_LLEG, IL_RLEG, IL_LFOOT, IL_RFOOT};

enum INJURYSEVERITY {IS_LOW, IS_SEVERE, IS_CRIPPLING};

class Injury{
public:
    INJURYTYPE type;
    INJURYLOC location;
    
    Injury();
};

#endif
