.\" Manpage for EterniaExec.
.\" Contact eternialogic@gmail.com to correct errors or typos.
.TH man 8 "28 Apr 2019" "1.1" "EterniaExec man page"
.SH NAME
EterniaExec \- Executable for EterniaLibrary (libEternia)
.SH SYNOPSIS
EterniaExec
.SH DESCRIPTION
EterniaLibrary Executable for further testing
.SH OPTIONS
None, all options are in a prompt "test"
.SH SEE ALSO
EterniaTest(8), EterniaLibrary(8)
.SH BUGS
Possibly many, unknown at this time.
.SH AUTHOR
Brent Clancy (eternialogic@gmail.com)
